Xml.namespace=XML Namespace
Xml.tag=Tag
Xml.attr=Attribute
JavaAnnotation.fqn=Annotation FQDN
JavaAnnotation.attr=Anno. Property

Xml.namespace.tip=XML namespace to match. Leave empty to match the default namespace. "*" for any namespace except the default.
Xml.tag.tip=XML tag name to match. Cannot be empty. "*" for any tag.
Xml.attr.tip=XML attribute whose value should navigate to code. Leave empty to navigate from the tag name. "*" for any attribute.
JavaAnnotation.fqn.tip=Fully qualified name of the Java annotation to search for. This value is required.
JavaAnnotation.attr.tip=Annotation attribute containing the target symbol name. Use "value" for the default property.

*.empty=Cannot be empty.
JavaAnnotation.attr.empty=Cannot be empty. Use string "value" for the default property.