xmlNamespace=Namespace
tagName=Tag
attributeName=Attribute
annotationFqdn=Annotation FQDN
annotationProperty=Anno. Property

xmlNamespace.tip=XML namespace to match. Leave empty to match the default namespace. "*" for any namespace except the default.
tagName.tip=XML tag name to match. Cannot be empty. "*" for any tag.
attributeName.tip=XML attribute whose value should navigate to code. Leave empty to navigate from the tag name. "*" for any attribute.
annotationFqdn.tip=Fully qualified name of the Java annotation to search for. This value is required.
annotationProperty.tip=Annotation attribute containing the target symbol name. Use "value" for the default property.

*.empty=Cannot be empty.
annotationProperty.empty=Cannot be empty. Use string "value" for the default property.